# Generated by Django 4.2 on 2024-02-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cropInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('H', models.CharField(max_length=100)),
                ('T', models.CharField(max_length=100)),
                ('N', models.CharField(max_length=100)),
                ('P', models.CharField(max_length=100)),
                ('K', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Farmer_name', models.CharField(max_length=100)),
                ('x1', models.CharField(blank=True, max_length=100)),
                ('x2', models.CharField(blank=True, max_length=100)),
                ('x3', models.CharField(blank=True, max_length=100)),
                ('x4', models.CharField(blank=True, max_length=100)),
                ('x5', models.CharField(blank=True, max_length=100)),
                ('x6', models.CharField(blank=True, max_length=100)),
                ('x7', models.CharField(blank=True, max_length=100)),
                ('x8', models.CharField(blank=True, max_length=100)),
                ('x9', models.CharField(blank=True, max_length=100)),
                ('x10', models.CharField(blank=True, max_length=100)),
                ('x11', models.CharField(blank=True, max_length=100)),
                ('x12', models.CharField(blank=True, max_length=100)),
                ('x13', models.CharField(blank=True, max_length=100)),
                ('x14', models.CharField(blank=True, max_length=100)),
                ('x15', models.CharField(blank=True, max_length=100)),
                ('x16', models.CharField(blank=True, max_length=100)),
                ('x17', models.CharField(blank=True, max_length=100)),
                ('x18', models.CharField(blank=True, max_length=100)),
                ('x19', models.CharField(blank=True, max_length=100)),
                ('x20', models.CharField(blank=True, max_length=100)),
                ('x21', models.CharField(blank=True, max_length=100)),
                ('x22', models.CharField(blank=True, max_length=100)),
                ('x24', models.CharField(blank=True, max_length=100)),
                ('x25', models.CharField(blank=True, max_length=100)),
                ('x26', models.CharField(blank=True, max_length=100)),
                ('x27', models.CharField(blank=True, max_length=100)),
                ('x28', models.CharField(blank=True, max_length=100)),
                ('x29', models.CharField(blank=True, max_length=100)),
                ('x30', models.CharField(blank=True, max_length=100)),
                ('x31', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
