# Generated by Django 4.2 on 2024-02-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0006_prediction_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropinfo',
            name='ph',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
